package com.deepika.list_test_rm_proj;

import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class combined_pojo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public combined_pojo() {
    }
    
    private java.util.List<java.lang.String> UDC = new ArrayList<String>();
    private java.lang.String strVal;
	public java.lang.String getStrVal() {
		return this.strVal;
	}

	public void setStrVal(java.lang.String strVal) {
		this.strVal = strVal;
	}



public java.util.List<java.lang.String> getUDC() {
		return this.UDC;
	}

	public void setUDC(java.lang.String input) {
			this.UDC.add(input);
	}



}