package com.deepika.list_test_rm_proj;

import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class combined_pojo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public combined_pojo() {
    }

private java.util.List<java.lang.String> UDC = new ArrayList<String>();

public java.util.List<java.lang.String> getUDC() {
		return this.UDC;
	}

	public void setUDC(java.lang.String input) {
			UDC.add(input);
	}


	public void add_element_UDC(String nnpd_attr_9) {
		UDC.add(nnpd_attr_9);
	}



}