package com.deepika.list_test_rm_proj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class combined_pojo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public combined_pojo() {
    }




}